spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/laosiji?characterEncoding=utf8&useSSL=true
    username: laosiji
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
#      uri: mongodb://root:pass@127.0.0.1:27017/lsj
      port: 27017
      host: 127.0.0.1
      username: laosiji
      password: laosiji123laosiji
      database: laosiji
yunbao:
  security:
      appSecurityProperty:
            client:
                auth2Clients[0]:
                    clientId: laosiji
                    clientSecret: laosiji
                    accessTokenValiditySeconds: 2500000
                    refreshTokenValiditySeconds: 5000000
                jwtkey: laosiji
server:
  port: 9090